# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitstart < Formula
  desc "A CLI tool for git project initialization."
  homepage "https://github.com/shinokada/gitstart"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shinokada/gitstart/releases/download/v1.0.4/gitstart_1.0.4_darwin_amd64.tar.gz"
      sha256 "c30d9f1d7dbfda715cd35339798e305b858336d37b8d967f27ab09dd897eb85e"

      define_method(:install) do
        bin.install "gitstart"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shinokada/gitstart/releases/download/v1.0.4/gitstart_1.0.4_darwin_arm64.tar.gz"
      sha256 "8184d177adfa5169e09810b2bb00edb35ea3563073e62c7fabe00ebec80a98e6"

      define_method(:install) do
        bin.install "gitstart"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shinokada/gitstart/releases/download/v1.0.4/gitstart_1.0.4_linux_amd64.tar.gz"
      sha256 "e6ca19258740d87d4cdc2a7ab3fec2db505d621f14a85e8f7bf632958fb5fcb1"
      define_method(:install) do
        bin.install "gitstart"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shinokada/gitstart/releases/download/v1.0.4/gitstart_1.0.4_linux_arm64.tar.gz"
      sha256 "8bc286d3396fa0ea9b475c33c20998352360147727455bf09936b1da86bd4190"
      define_method(:install) do
        bin.install "gitstart"
      end
    end
  end

  test do
    system "#{bin}/gitstart", "version"
  end
end
