# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitstart < Formula
  desc "A CLI tool for git project initialization."
  homepage "https://github.com/shinokada/gitstart"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shinokada/gitstart/releases/download/v1.1.0/gitstart_1.1.0_darwin_amd64.tar.gz"
      sha256 "7cd9f06ec3809ed55b8b657c04c7c3fe852d44de19dffa2970783a94563a2a91"

      define_method(:install) do
        bin.install "gitstart"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shinokada/gitstart/releases/download/v1.1.0/gitstart_1.1.0_darwin_arm64.tar.gz"
      sha256 "e9ccbcc58b7944f8ba08dd28609fe2a6e772977259ffcaa39330f6c64762b795"

      define_method(:install) do
        bin.install "gitstart"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shinokada/gitstart/releases/download/v1.1.0/gitstart_1.1.0_linux_amd64.tar.gz"
      sha256 "74554031de7ed632ebd515c9031c724808631b675ab3581507e713f235d9d59e"
      define_method(:install) do
        bin.install "gitstart"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shinokada/gitstart/releases/download/v1.1.0/gitstart_1.1.0_linux_arm64.tar.gz"
      sha256 "3186f1785c55a508b3b38758e43117aa190dbff33d93a9b07ce00e1c954f3b8d"
      define_method(:install) do
        bin.install "gitstart"
      end
    end
  end

  test do
    system "#{bin}/gitstart", "version"
  end
end
